framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    stream: "messages"
        routing:
            #'App\Core\Domain\Event\WalletEventCreated': async
